### ISSUE TITLE
staying sync with _s

### ISSUE THREAD

**Issue by pjv** [luclemo/Styl_s#1]
Hi, great idea.

Do you have a plan for staying synced with _s as it changes?

**Comment by luclemo** [comment]
Hey there,

The changes from one version of _s to the next are generally pretty minor. I don't have a plan to stay in sync beyond doing a quick diff once in awhile and seeing if there's anything new worth porting over. Unlikely to be any major updates to the styles ;)

Having said that we'll see if they come out with a branch leveraging the WP-API.
